//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BookKeeper.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class AddStatisticOfDate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "statistics_of_dates",
                schema: "bookkeeper",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    date_on_utc = table.Column<DateOnly>(type: "date", nullable: false),
                    total_expend_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    total_income_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    sum_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    user_id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_statistics_of_dates", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_statistics_of_date_user_id_date_on_utc",
                schema: "bookkeeper",
                table: "statistics_of_dates",
                columns: new[] { "user_id", "date_on_utc" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "statistics_of_dates",
                schema: "bookkeeper");
        }
    }
}
