//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BookKeeper.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class ChangeIdentitySchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "identity");

            migrationBuilder.RenameTable(
                name: "refresh_tokens",
                schema: "bookkeeper",
                newName: "refresh_tokens",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_users",
                schema: "bookkeeper",
                newName: "asp_net_users",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_tokens",
                schema: "bookkeeper",
                newName: "asp_net_user_tokens",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_roles",
                schema: "bookkeeper",
                newName: "asp_net_user_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_logins",
                schema: "bookkeeper",
                newName: "asp_net_user_logins",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_claims",
                schema: "bookkeeper",
                newName: "asp_net_user_claims",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_roles",
                schema: "bookkeeper",
                newName: "asp_net_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_role_claims",
                schema: "bookkeeper",
                newName: "asp_net_role_claims",
                newSchema: "identity");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "refresh_tokens",
                schema: "identity",
                newName: "refresh_tokens",
                newSchema: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "asp_net_users",
                schema: "identity",
                newName: "asp_net_users",
                newSchema: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "asp_net_user_tokens",
                schema: "identity",
                newName: "asp_net_user_tokens",
                newSchema: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "asp_net_user_roles",
                schema: "identity",
                newName: "asp_net_user_roles",
                newSchema: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "asp_net_user_logins",
                schema: "identity",
                newName: "asp_net_user_logins",
                newSchema: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "asp_net_user_claims",
                schema: "identity",
                newName: "asp_net_user_claims",
                newSchema: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "asp_net_roles",
                schema: "identity",
                newName: "asp_net_roles",
                newSchema: "bookkeeper");

            migrationBuilder.RenameTable(
                name: "asp_net_role_claims",
                schema: "identity",
                newName: "asp_net_role_claims",
                newSchema: "bookkeeper");
        }
    }
}
