//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BookKeeper.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class CreateStatistic : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "statistics_of_months",
                schema: "bookkeeper",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    month = table.Column<int>(type: "integer", nullable: false),
                    total_expend_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    total_income_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    sum_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    user_id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_statistics_of_months", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "statistics_of_weeks",
                schema: "bookkeeper",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    month = table.Column<int>(type: "integer", nullable: false),
                    week_of_month = table.Column<int>(type: "integer", nullable: false),
                    total_expend_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    total_income_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    sum_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    user_id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_statistics_of_weeks", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "statistics_of_years",
                schema: "bookkeeper",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    total_expend_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    total_income_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    sum_amount = table.Column<decimal>(type: "numeric(18,0)", precision: 18, scale: 0, nullable: false),
                    user_id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_statistics_of_years", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_statistics_of_month_user_id_year_month",
                schema: "bookkeeper",
                table: "statistics_of_months",
                columns: new[] { "user_id", "year", "month" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_statistics_of_week_user_id_year_month_week",
                schema: "bookkeeper",
                table: "statistics_of_weeks",
                columns: new[] { "user_id", "year", "month", "week_of_month" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_statistics_of_year_user_id_year",
                schema: "bookkeeper",
                table: "statistics_of_years",
                columns: new[] { "user_id", "year" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "statistics_of_months",
                schema: "bookkeeper");

            migrationBuilder.DropTable(
                name: "statistics_of_weeks",
                schema: "bookkeeper");

            migrationBuilder.DropTable(
                name: "statistics_of_years",
                schema: "bookkeeper");
        }
    }
}
